routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();


Route::name('app.')->middleware('auth')->group(function(){
    Route::get('/', 'DashboardController@dashboard')->name('dashboard');
    Route::get('/dashboard', 'DashboardController@dashboard')->name('dashboard');

    Route::name('staffs.')->prefix('staffs')->group(function(){
       Route::get('/', 'StaffsController@listStaffsPage')->name('list');

       Route::get('save/{staff?}', 'StaffsController@saveStaffPage')->name('save');
       Route::post('submit', 'StaffsController@register')->name('submit');
       Route::get('{staff}/delete', 'StaffsController@deleteStaff')->name('delete');
    });

    Route::name('students.')->prefix('students')->group(function(){
        Route::get('/', 'StudentController@listStudentsPage')->name('list');
        Route::get('{student}/preview-clearance', 'StudentController@previewStudentClearance')->name('preview');
    });

    Route::name('signatories.')->prefix('signatories')->group(function(){
        Route::get('/', 'SignatoriesController@listStaffsPage')->name('list');
        Route::get('save/{signatory?}', 'SignatoriesController@saveSignatoryPage')->name('save');
        Route::post('submit', 'SignatoriesController@saveSignatory')->name('submit');

    });

    Route::name('clearance.')->prefix('clearance')->group(function(){
        Route::post('sign', 'ClearanceController@signClearanceForm')->name('sign');

    });
});



Route::post('students/registration', 'StudentController@register')->name('student.registration');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function dashboard()
    {
        /** @var User $user */
        $user = auth()->user();

        $dashboard_view_file = 'student';

        if($user->hasRole(config('system.roles.staff'))) $dashboard_view_file = 'staff';
        if($user->hasRole(config('system.roles.admin'))) $dashboard_view_file = 'admin';

        return view('app.dashboard.' . $dashboard_view_file);
    }
}

resources/views/app/dashboard/admin.blade.php
@extends('layouts.app')

@section('app.header')
    <!-- Header -->
    <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center"
         style="min-height: 600px; background-image: url(../assets/img/theme/profile-cover.jpg); background-size: cover; background-position: center top;">
        <!-- Mask -->
        <span class="mask bg-gradient-default opacity-8"></span>
        <!-- Header container -->
        <div class="container-fluid d-flex align-items-center">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <h1 class="display-2 text-white">{{greeting(auth()->user()->person->surname)}}</h1>
                    <p class="text-white mt-0 mb-5">
                        Welcome to your account. As an Admin, you manage students, staffs and clearance data
                    </p>
                    {{--<a href="#!" class="btn btn-info">Edit profile</a>--}}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('app.content')
    <!-- Card stats -->
    <div class="row">
        <div class="col-xl-3 col-lg-6">
            <div class="card card-stats mb-4 mb-xl-0">
                <div class="card-body">
                    <div class="row">
                        <div class="col">
                            <h5 class="card-title text-uppercase text-muted mb-0">Registered Students</h5>
                            <span class="h2 font-weight-bold mb-0">
                                {{\App\Repositories\StudentsRepository::init()->getTotalStudents()}}
                            </span>
                        </div>
                        <div class="col-auto">
                            <div class="icon icon-shape bg-danger text-white rounded-circle shadow">
                                <i class="fas fa-users"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-6">
            <div class="card card-stats mb-4 mb-xl-0">
                <div class="card-body">
                    <div class="row">
                        <div class="col">
                            <h5 class="card-title text-uppercase text-muted mb-0">Registered Staffs</h5>
                            <span class="h2 font-weight-bold mb-0">
                                {{\App\Repositories\StaffsRepository::init()->getTotalStaffs()}}
                            </span>
                        </div>
                        <div class="col-auto">
                            <div class="icon icon-shape bg-warning text-white rounded-circle shadow">
                                <i class="fas fa-user-secret"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-6">
            <div class="card card-stats mb-4 mb-xl-0">
                <div class="card-body">
                    <div class="row">
                        <div class="col">
                            <h5 class="card-title text-uppercase text-muted mb-0">Clearance Applications</h5>
                            <span class="h2 font-weight-bold mb-0">
                                {{\App\Repositories\ClearanceRepository::init()->getTotalClearance()}}
                            </span>
                        </div>
                        <div class="col-auto">
                            <div class="icon icon-shape bg-yellow text-white rounded-circle shadow">
                                <i class="fas fa-file-archive"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-6">
            <div class="card card-stats mb-4 mb-xl-0">
                <div class="card-body">
                    <div class="row">
                        <div class="col">
                            <h5 class="card-title text-uppercase text-muted mb-0">
                                Incomplete Clearance
                            </h5>
                            <span class="h2 font-weight-bold mb-0">
                                {{\App\Repositories\ClearanceRepository::init()->getTotalPendingClearance()}}
                            </span>
                        </div>
                        <div class="col-auto">
                            <div class="icon icon-shape bg-info text-white rounded-circle shadow">
                                <i class="fas fa-percent"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/app/dashboard/staff.blade.php
@extends('layouts.app')

@section('app.header')
    <!-- Header -->
    <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" >
        <!-- Mask -->
        <span class="mask bg-gradient-default opacity-8"></span>
        <!-- Header container -->
        <div class="container-fluid d-flex align-items-center">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <h1 class="display-2 text-white">{{greeting(auth()->user()->person->surname)}}</h1>
                    <p class="text-white mt-0 mb-5">
                        Welcome to your account. Here you can see / sign available clearance forms.
                        @if(auth()->user()->person->department)
                            <br>
                        <span class="text-info">Department: {{auth()->user()->person->department->name}}</span>
                        @endif
                        @if(auth()->user()->person->isInRole(config('system.roles.officer')))
                            <br>
                            <span class="text-info">Office: {{auth()->user()->person->signatory_offices()->first()->office}}</span>
                        @endif
                    </p>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('app.content')
    <div class="row mt-1">
        <div class="col-xl-12 mb-5 mb-xl-0">
            <div class="card shadow">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col">
                            <h3 class="mb-0">Students for clearance</h3>
                        </div>
                        <div class="col text-right">

                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <!-- Projects table -->
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">Student</th>
                            <th scope="col">Department</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach(\App\Repositories\ClearanceRepository::init()->getAvailableClearanceForOfficer(auth()->user()->person) as $clearance)
                        <tr>
                            <td>
                                {{$loop->index + 1}}
                            </td>
                            <th scope="row">
                                {{$clearance->student->getFullName()}}
                            </th>
                            <td>
                                {{$clearance->student->department->name}}
                            </td>
                            <td>
                                <form action="{{route('app.clearance.sign')}}" class="form-inline d-inline-block" method="post">
                                    @csrf
                                    <input type="hidden" name="clearance_id" value="{{$clearance->id}}">

                                    @if(auth()->user()->person->isInRole(config('system.roles.dept_admin')))
                                        <input type="hidden" name="signatory_office_id"
                                               value="{{\App\Repositories\SignatoryRepository::init()->getSignatoryByName('Department')->id}}">
                                    @else
                                        <input type="hidden" name="signatory_office_id"
                                               value="{{auth()->user()->person->signatory_offices()->first()->id}}">
                                    @endif

                                    <input type="hidden" name="staff" value="{{auth()->user()->id}}">
                                    <button class="btn btn-sm btn-outline-warning" type="submit">Sign</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/app/dashboard/student.blade.php
@extends('layouts.app')

@section('app.header')
    <!-- Header -->
    <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" >
        <!-- Mask -->
        <span class="mask bg-gradient-default opacity-8"></span>
        <!-- Header container -->
        <div class="container-fluid d-flex align-items-center">
            <div class="row">
                <div class="col-lg-9 col-md-10">
                    <h1 class="display-2 text-white">{{greeting(auth()->user()->person->surname)}}</h1>
                    <p class="text-white mt-0 mb-5">
                        Welcome to your account. You can see the progress made on your final year student clearance
                    </p>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('app.content')
    <div class="row mt-1">
        <div class="col-xl-12 mb-5 mb-xl-0">
            <div class="card shadow">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col">
                            <h3 class="mb-0">Clearance</h3>
                        </div>
                        <div class="col text-right">
                            <a href="{{route('app.students.preview', ['student' => auth()->user()->person->id])}}"
                               onclick="var popup_window = window.open(this.href, 'mywin','location=0,toolbar=0,menubar=0,scrollbars=1,height=600,width=1000');
                           return false;"
                               class="btn btn-sm btn-primary"><i class="fas fa-print"></i>
                            Preview / Print
                            </a>
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">Office</th>
                            <th scope="col">Signed On</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach(auth()->user()->person->clearance_signatures as $clearance_signature)
                            <tr class="text-{{$clearance_signature->signed ? 'default' : 'warning'}}">
                                <td>
                                    {{$loop->index + 1}}
                                </td>
                                <th scope="row">
                                    {{$clearance_signature->office->name}}
                                </th>
                                <td>
                                    {{$clearance_signature->signed_on ? $clearance_signature->signed_on->format('jS F, Y') : ''}}
                                </td>
                                <td>
                                    @if($clearance_signature->signed)
                                    <i class="fas fa-check-circle fa-2x text-success"></i>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection