routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();


Route::name('app.')->middleware('auth')->group(function(){
    Route::get('/', 'DashboardController@dashboard')->name('dashboard');
    Route::get('/dashboard', 'DashboardController@dashboard')->name('dashboard');

    Route::name('staffs.')->prefix('staffs')->group(function(){
       Route::get('/', 'StaffsController@listStaffsPage')->name('list');

       Route::get('save/{staff?}', 'StaffsController@saveStaffPage')->name('save');
       Route::post('submit', 'StaffsController@register')->name('submit');
       Route::get('{staff}/delete', 'StaffsController@deleteStaff')->name('delete');
    });

    Route::name('students.')->prefix('students')->group(function(){
        Route::get('/', 'StudentController@listStudentsPage')->name('list');
        Route::get('{student}/preview-clearance', 'StudentController@previewStudentClearance')->name('preview');
    });

    Route::name('signatories.')->prefix('signatories')->group(function(){
        Route::get('/', 'SignatoriesController@listStaffsPage')->name('list');
        Route::get('save/{signatory?}', 'SignatoriesController@saveSignatoryPage')->name('save');
        Route::post('submit', 'SignatoriesController@saveSignatory')->name('submit');

    });

    Route::name('clearance.')->prefix('clearance')->group(function(){
        Route::post('sign', 'ClearanceController@signClearanceForm')->name('sign');

    });
});



Route::post('students/registration', 'StudentController@register')->name('student.registration');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

resources/views/app/partials/alerts.blade.php
@push('scripts')
    @unless($errors->isEmpty())
        <script type="text/javascript">
            jQuery(document).ready(function () {
                Swal.fire({
                    title: '<strong>Error</strong>',
                    type: 'error',
                    html:'{!! listArrayInHtml($errors->all()) !!}',
                    showCloseButton: true,
                    // showCancelButton: true,
                    focusConfirm: false,
                })
            });
        </script>
    @endunless

    @include('flash::message')
@endpush

resources/views/app/partials/sidebar.blade.php
<!-- Sidenav -->
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        <a class="navbar-brand pt-0" href="/">
            <img src="/img/mcu_logo.jpeg" class="navbar-brand-img" alt="..." style="height: 80px;
    max-height: none;">
        </a>

        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Navigation -->
            <h6 class="navbar-heading text-muted">
                Logged in as:
                {{implode(', ', auth()->user()->getRoleNames()->toArray())}}
            </h6>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/">
                        <i class="ni ni-tv-2 text-primary"></i> Dashboard
                    </a>
                </li>
                @if(auth()->user()->hasRole(config('system.roles.admin')))
                <li class="nav-item">
                    <a class="nav-link" href="{{route('app.staffs.list')}}">
                        <i class="ni ni-circle-08 text-primary"></i> Staffs
                    </a>
                </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('app.students.list')}}">
                            <i class="ni ni-circle-08 text-primary"></i> Students
                        </a>
                    </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{route('app.signatories.list')}}">
                        <i class="ni ni-ruler-pencil text-primary"></i> Offices (Signatories)
                    </a>
                </li>
                @endif
                <li class="nav-item">
                    <a class="nav-link" href="/">
                        <i class="ni ni-tv-2 text-primary"></i> Change Password
                    </a>
                </li>
                <li class="nav-item ">
                    <!-- Divider -->
                    <hr class="my-3">
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/logout">
                        <i class="ni ni-key-25 text-info"></i> Logout
                    </a>
                </li>
            </ul>


        </div>
    </div>
</nav>

resources/views/app/partials/topnav.blade.php
<!-- Top navbar -->
<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
        <!-- Brand -->
        <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" href="{{route('app.dashboard')}}">
            {{$pageTitle ?? 'Dashboard'}}
        </a>
        <!-- User -->
        <ul class="navbar-nav align-items-center d-none d-md-flex">
            <li class="nav-item dropdown">
                <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="media align-items-center">
                <span class="avatar avatar-sm rounded-circle">
                    @if(auth()->user()->person->photo_url)
                  <img alt="Image placeholder" src="{{auth()->user()->person->getPhotoUrl()}}">
                    @endif
                </span>
                        <div class="media-body ml-2 d-none d-lg-block">
                            <span class="mb-0 text-sm  font-weight-bold">{{auth()->user()->getFullName()}}</span>
                        </div>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                    <div class=" dropdown-header noti-title">
                        <h6 class="text-overflow m-0">Welcome!</h6>
                    </div>

                    <a href="./examples/profile.html" class="dropdown-item">
                        <i class="ni ni-calendar-grid-58"></i>
                        <span>Activity</span>
                    </a>
                    <a href="./examples/profile.html" class="dropdown-item">
                        <i class="ni ni-support-16"></i>
                        <span>Support</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="/logout" class="dropdown-item">
                        <i class="ni ni-user-run"></i>
                        <span>Logout</span>
                    </a>
                </div>
            </li>
        </ul>
    </div>
</nav>