routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();


Route::name('app.')->middleware('auth')->group(function(){
    Route::get('/', 'DashboardController@dashboard')->name('dashboard');
    Route::get('/dashboard', 'DashboardController@dashboard')->name('dashboard');

    Route::name('staffs.')->prefix('staffs')->group(function(){
       Route::get('/', 'StaffsController@listStaffsPage')->name('list');

       Route::get('save/{staff?}', 'StaffsController@saveStaffPage')->name('save');
       Route::post('submit', 'StaffsController@register')->name('submit');
       Route::get('{staff}/delete', 'StaffsController@deleteStaff')->name('delete');
    });

    Route::name('students.')->prefix('students')->group(function(){
        Route::get('/', 'StudentController@listStudentsPage')->name('list');
        Route::get('{student}/preview-clearance', 'StudentController@previewStudentClearance')->name('preview');
    });

    Route::name('signatories.')->prefix('signatories')->group(function(){
        Route::get('/', 'SignatoriesController@listStaffsPage')->name('list');
        Route::get('save/{signatory?}', 'SignatoriesController@saveSignatoryPage')->name('save');
        Route::post('submit', 'SignatoriesController@saveSignatory')->name('submit');

    });

    Route::name('clearance.')->prefix('clearance')->group(function(){
        Route::post('sign', 'ClearanceController@signClearanceForm')->name('sign');

    });
});



Route::post('students/registration', 'StudentController@register')->name('student.registration');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

app/Staff.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Staff extends Model
{
    protected $table = 'staff';

    protected $guarded = ['id'];

    public function account()
    {
        return $this->morphOne(User::class,'person');
    }

    public function department()
    {
        return $this->belongsTo(Department::class,'department_id');
    }

    public function signatory_offices()
    {
        return $this->hasMany(Signatory::class,'staff_id');
    }

    public function getFullName()
    {
        return $this->surname . ' ' . $this->other_names;
    }

    public function isInDepartment($department)
    {
        return $this->department->name == $department;
    }

    public function isInRole($role)
    {
        return $this->account()->role($role)->exists();
    }
}

app/Http/Controllers/StaffsController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\StaffsRepository;
use App\Staff;
use Illuminate\Foundation\Auth\RegistersUsers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class StaffsController extends Controller
{
    use RegistersUsers;

    public function listStaffsPage()
    {
        $staffs = StaffsRepository::init()->getAllStaffs();

        return view('app.staffs.list', compact('staffs'));
    }

    public function deleteStaff(Staff $staff)
    {
        try {
            $staff->delete();

            flash()->info('Deleted!');

            return redirect()->back();

        } catch (\Exception $e) {

            flash()->warning($e->getMessage());

            return redirect()->back();
        }
    }

    public function saveStaffPage(Staff $staff = null)
    {
        return view('app.staffs.edit', compact('staff'));
    }


    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'same:retype_password'],
            'surname' => ['required', 'string'],
            'other_names' => ['required', 'string'],
//            'photo' => ['required', 'image'],
            'phone' => ['required', 'string'],
            'department' => ['sometimes'],
            'role' => ['sometimes'],
        ]);
    }

    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return \App\Staff
     */
    protected function create(array $data)
    {
        $staffRepo = StaffsRepository::init();

        $staff = $staffRepo->createStaff([
            'surname' => $data['surname'],
            'other_names' => $data['other_names'],
            'email' => $data['email'],
            'phone' => $data['phone'],
            'department_id' => $data['department'],
            'username' => $data['username'],
            'password' => $data['password'],
            'role' => $data['role'],
        ]);

        /*// todo: save student photo
        $uploaded_image = $data['photo'];
        $filename = time() . '.' . $uploaded_image->clientExtension();
        $path = FileRepository::init()->saveFileAs($uploaded_image, $filename);
        $student->fill([
            'photo_url' => $path
        ]);
        $student->save();*/

        return $staff;
    }

    public function register(Request $request)
    {
        $this->validator($request->all())->validate();

        $user = $this->create($request->all());

        return $this->registered($request, $user)
            ?: redirect($this->redirectPath());
    }

    /**
     * The student has been registered.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Staff $staff
     * @return mixed
     */
    protected function registered(Request $request, Staff $staff)
    {
        flash()->success($staff->getFullName() . ' has been successfully saved');

        return redirect()->back();
    }
}

resources/views/app/staffs/edit.blade.php
@extends('layouts.base')

@php
    $pageTitle = $staff ? $staff->title : 'New Staff';
@endphp

@section('base')
    <div class="row justify-content-center">
        <div class="col-lg-9 col-md-9">
            <div class="card bg-secondary shadow">
                <div class="card-header bg-white border-0">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0">Staff Registration</h3>
                        </div>
                        <div class="col-4 text-right">
                            {{--<a href="#!" class="btn btn-sm btn-primary">Settings</a>--}}
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data" action="{{route('app.staffs.submit')}}">
                        @csrf
                        @if(isset($staff))
                            <input type="hidden" name="id" value="{{$staff->id}}">
                        @endif
                        <h6 class="heading-small text-muted mb-4">Staff information</h6>
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="input-first-name">Surname</label>
                                        <input type="text" id="input-first-name"
                                               name="surname"
                                               class="form-control form-control-alternative"
                                               placeholder="Surname" value="{{$staff->surname ?? old('surname')}}">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="input-last-name">Other names:</label>
                                        <input type="text" id="input-last-name"
                                               class="form-control form-control-alternative"
                                               name="other_names"
                                               placeholder="Other names" value="{{$staff->other_names ?? old('other_names')}}">
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="input-phone">Phone:</label>
                                        <input type="text" id="input-phone"
                                               class="form-control form-control-alternative"
                                               placeholder="Phone:" value="{{$staff->phone ?? old('phone')}}" name="phone">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="input-email">Email address</label>
                                        <input type="email" id="input-email"
                                               name="email"
                                               value="{{$staff->email ?? old('email')}}"
                                               class="form-control form-control-alternative" placeholder="Email:">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr class="my-4" />

                        <h6 class="heading-small text-muted mb-4">Account information</h6>

                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="input-username">Username:</label>
                                        <input type="text" id="input-username"
                                               class="form-control form-control-alternative"
                                               name="username"
                                               placeholder="Username">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="input-password">Password:</label>
                                        <input type="password" id="input-password"
                                               class="form-control form-control-alternative"
                                               name="password"
                                               placeholder="">
                                    </div>
                                </div>

                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="input-retype-password">Retype Password:</label>
                                        <input type="password" id="input-retype-password"
                                               class="form-control form-control-alternative"
                                               name="retype_password"
                                               placeholder="">
                                    </div>
                                </div>

                            </div>
                        </div>

                        <hr class="my-4" />

                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="form-control-label" for="input-department">Department:</label>
                                    <select class="form-control custom-select" name="department" id="input-department">
                                        <option value="">Pick a department</option>

                                    @foreach(\App\Repositories\DepartmentRepository::init()->getAllDepartments() as $department)
                                            <option value="{{$department->id}}">{{$department->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="form-control-label" for="input-department">Role:</label>
                                    <select class="form-control custom-select" name="role" id="input-department">
                                        <option>Pick a role</option>

                                        @foreach(\Spatie\Permission\Models\Role::whereNotIn('name',
                                        [config('system.roles.student'), config('system.roles.staff'), config('system.roles.admin')])->get() as $role)
                                            <option value="{{$role->id}}">{{$role->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            {{--<div class="col-lg-5">
                                <div class="form-group">
                                    <label class="form-control-label" for="input-passport-photo">Upload passport photo:</label>
                                    <input type="file" id="input-passport-photo"
                                           class="form-control form-control-alternative"
                                           name="photo" accept="image/jpeg, image/png, image/jpg"
                                           placeholder="">
                                </div>
                            </div>--}}
                        </div>

                        <hr class="my-4" />

                        <div class="text-center">
                            <button type="submit" class="btn btn-primary my-4">Submit</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
@endsection

@section('header') @overwrite
@section('footer') @overwrite

resources/views/app/staffs/list.blade.php
@extends('layouts.app')

@php
$pageTitle = 'Staffs';
@endphp

@section('app.header')
    <!-- Header -->
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row">
                    <div class="col-lg-9 col-md-10">
                        <h1 class="display-2 text-white">
                            {{$pageTitle}}
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('app.content')
    <div class="row mt-1">
        <div class="col-xl-12 mb-5 mb-xl-0">
            <div class="card shadow">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col">
                            <h3 class="mb-0">Staffs</h3>
                        </div>
                        <div class="col text-right">
                            <a href="{{route('app.staffs.save')}}"
                               onclick="var popup_window = window.open(this.href, 'mywin','location=0,toolbar=0,menubar=0,scrollbars=1,height=600,width=700');
                           // popup_window.onbeforeunload = reloadParentWindow;
                           return false;"
                               class="btn btn-sm btn-primary">New Staff</a>
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <!-- Projects table -->
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">Names</th>
                            <th scope="col">Email</th>
                            <th scope="col">Department</th>
                            <th scope="col">Office</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($staffs as $staff)
                        <tr>
                            <td>
                                {{$loop->index + 1}}
                            </td>
                            <th scope="row">
                                {{$staff->getFullName()}}
                            </th>
                            <td>
                                {{$staff->email}}
                            </td>
                            <td>
                                @if($staff->department)
                                    {{$staff->department->name}}
                                @endif
                            </td>
                            <td>
                                @if($staff->isInRole(config('system.roles.officer')))
                                    {{$staff->signatory_offices()->first()->office ?? ''}}
                                @endif
                            </td>
                            <td>
                                <a href="{{route('app.staffs.delete', ['staff'=>$staff->id])}}"
                                   class="btn btn-sm btn-danger" onclick="return confirm('Are you sure?')">
                                    Delete
                                </a>
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection