routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();


Route::name('app.')->middleware('auth')->group(function(){
    Route::get('/', 'DashboardController@dashboard')->name('dashboard');
    Route::get('/dashboard', 'DashboardController@dashboard')->name('dashboard');

    Route::name('staffs.')->prefix('staffs')->group(function(){
       Route::get('/', 'StaffsController@listStaffsPage')->name('list');

       Route::get('save/{staff?}', 'StaffsController@saveStaffPage')->name('save');
       Route::post('submit', 'StaffsController@register')->name('submit');
       Route::get('{staff}/delete', 'StaffsController@deleteStaff')->name('delete');
    });

    Route::name('students.')->prefix('students')->group(function(){
        Route::get('/', 'StudentController@listStudentsPage')->name('list');
        Route::get('{student}/preview-clearance', 'StudentController@previewStudentClearance')->name('preview');
    });

    Route::name('signatories.')->prefix('signatories')->group(function(){
        Route::get('/', 'SignatoriesController@listStaffsPage')->name('list');
        Route::get('save/{signatory?}', 'SignatoriesController@saveSignatoryPage')->name('save');
        Route::post('submit', 'SignatoriesController@saveSignatory')->name('submit');

    });

    Route::name('clearance.')->prefix('clearance')->group(function(){
        Route::post('sign', 'ClearanceController@signClearanceForm')->name('sign');

    });
});



Route::post('students/registration', 'StudentController@register')->name('student.registration');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

app/Signatory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Signatory extends Model
{
    protected $guarded = ['id'];

    protected $table = 'signatories';

    public function staff()
    {
        return $this->belongsTo(Staff::class);
    }
}

app/Http/Controllers/SignatoriesController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\SignatoryRepository;
use App\Signatory;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;

class SignatoriesController extends Controller
{
    public function listStaffsPage()
    {
        $signatories = SignatoryRepository::init()->getAllSignatories();

        return view('app.signatories.list', compact('signatories'));
    }

    public function saveSignatoryPage(Signatory $signatory = null)
    {
        return view('app.signatories.edit', compact('signatory'));
    }

    public function saveSignatory()
    {
        $data = \request()->all();

        $signatory = Signatory::find($data['id']);

        $signatory->fill([
            'staff_id' => $data['staff']
        ]);

        $signatory->save();

        if($signatory->staff){
            flash()->success($signatory->staff->getFullName() . ' has been assigned to ' . $signatory->name);
        } else {
            flash()->success($signatory->name . ' has been updated');
        }

        return redirect()->back();
    }
}

resources/views/app/signatories/edit.blade.php
@extends('layouts.base')

@php
    $pageTitle = $signatory ? $signatory->title : 'New Office (Signatory)';
@endphp

@section('base')
    <div class="row justify-content-center">
        <div class="col-lg-9 col-md-9">
            <div class="card bg-secondary shadow">
                <div class="card-header bg-white border-0">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0">Office (Signatory) Registration</h3>
                        </div>
                        <div class="col-4 text-right">
                            {{--<a href="#!" class="btn btn-sm btn-primary">Settings</a>--}}
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data" action="{{route('app.signatories.submit')}}">
                        @csrf
                        @if(isset($signatory))
                            <input type="hidden" name="id" value="{{$signatory->id}}">
                        @endif
                        <h6 class="heading-small text-muted mb-4">Office (Signatory) information</h6>
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="input-first-name">Name</label>
                                        <input type="text" id="input-first-name"
                                               readonly
                                               class="form-control form-control-alternative"
                                               placeholder="Surname" value="{{$signatory->name ?? old('name')}}">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="input-department">Staff:</label>
                                        <select class="form-control custom-select" name="staff" id="input-department">
                                            <option value="">Pick a staff</option>
                                            @foreach(\App\Repositories\StaffsRepository::init()->getAllStaffOfficers() as $staff)
                                                <option value="{{$staff->id}}"
                                                @if($signatory && $signatory->staff_id == $staff->id)
                                                    selected
                                                @elseif(old('staff') == $staff->id)
                                                    selected
                                                @endif
                                                >
                                                    {{$staff->getFullName()}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <hr class="my-4" />

                        <div class="text-center">
                            <button type="submit" class="btn btn-primary my-4">Submit</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
@endsection

@section('header') @overwrite
@section('footer') @overwrite

resources/views/app/signatories/list.blade.php
@extends('layouts.app')

@php
$pageTitle = 'Offices (Signatories)';
@endphp

@section('app.header')
    <!-- Header -->
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row">
                    <div class="col-lg-9 col-md-10">
                        <h1 class="display-2 text-white">
                            {{$pageTitle}}
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('app.content')
    <div class="row mt-1">
        <div class="col-xl-12 mb-5 mb-xl-0">
            <div class="card shadow">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col">
                            <h3 class="mb-0">List of offices</h3>
                        </div>
                        <div class="col text-right">

                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <!-- Projects table -->
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">Name</th>
                            <th scope="col">Staff</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($signatories as $signatory)
                        <tr>
                            <td>
                                {{$loop->index + 1}}
                            </td>
                            <th scope="row">
                                {{$signatory->name}}
                            </th>
                            <td>
                                @if($signatory->name == 'Department')
                                Not Applicable
                                @else
                                    {{$signatory->staff ? $signatory->staff->getFullName() : 'Not set'}}
                                @endif
                            </td>
                            <td>
                                {{--<a href="{{route('app.staffs.delete', ['staff'=>$staff->id])}}"
                                   class="btn btn-sm btn-danger" onclick="return confirm('Are you sure?')">
                                    Delete
                                </a>--}}
                                @if($signatory->name != 'Department')
                                    <a href="{{route('app.signatories.save', ['signatory' => $signatory->id])}}"
                                       onclick="var popup_window = window.open(this.href, 'mywin','location=0,toolbar=0,menubar=0,scrollbars=1,height=600,width=700');
                           // popup_window.onbeforeunload = reloadParentWindow;
                           return false;"
                                       class="btn btn-sm btn-primary">Assign Staff to office</a>
                            </td>
                                @endif

                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection